---
# Elasticache Redis with cluster mode enabled
---
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
metadata:
  name: redis-clustermode-on
  labels:
    clustermode: "on"
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-north-1
    replicationGroupDescription: "Cluster mode enabled"
    applyModificationsImmediately: true
    engine: "redis"
    engineVersion: "6.2"
    port: 6379
    cacheSubnetGroupNameRef:
      name: subnet-group
    # numCacheClusters: 2
    cacheParameterGroupName: clustermode-on
    cacheNodeType: cache.t3.micro
    automaticFailoverEnabled: true
    multiAZEnabled: true
    # numCacheClusters: 1
    # Replica nodes in each node group/shard
    replicasPerNodeGroup: 1
    securityGroupIdRefs:
      - name: elasticache-redis
    # securityGroupIds:
    #   - sg-06724db1c96051880
  writeConnectionSecretToRef:
    name: redis-clustermode-on
    namespace: crossplane-system
  providerConfigRef:
    name: provider-aws
