---
# CronJob to delete expired snapshots
# Uses the same service account as the cronjob that creates the snapshots
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rds-clear-snapshots
  namespace: default
  labels:
    cronjob: rds-clear-snapshots
spec:
  # Twice a day
  schedule: "0 08,20 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-rds-snapshot
          containers:
          - name: rds-clear-snapshots
            # Image name seems to need to be quoted, even though some examples don't do that
            image: "kahu/rdsdeletesnapshot:v1.0.5"
            imagePullPolicy: IfNotPresent
            # No envars needed so none defined
            # Nor any args
          restartPolicy: Never
---
